SELECT *
FROM [Portfolio Projects]..[Miami Dade POs 2022]
Order by PO_NUMBER

SELECT DISTINCT(PO_NUMBER), SUPPLIER_NAME, BUSINESS_UNIT
FROM [Portfolio Projects]..[Miami Dade POs 2022]

-- PO numbers can contain multiple suppliers and multiple business units--

SELECT SUPPLIER_NAME, SUM(PO_AMOUNT) AS "TOTAL AMT OF PURCHASES"
FROM [Portfolio Projects]..[Miami Dade POs 2022]
GROUP BY SUPPLIER_NAME
ORDER BY SUM(PO_AMOUNT) DESC

SELECT SUPPLIER_NAME, COUNT(DISTINCT(PO_NUMBER)) AS "# OF ORDERS", AVG(PO_AMOUNT) AS "AVG ORDER AMT"
FROM [Portfolio Projects]..[Miami Dade POs 2022]
GROUP BY SUPPLIER_NAME
ORDER BY COUNT(DISTINCT(PO_NUMBER)) DESC

SELECT ITEM_CATEGORY, COUNT(DISTINCT(PO_NUMBER)) AS "# OF ORDERS", SUM(PO_QUANTITY) AS "TOTAL QTY ORDERED", AVG(PO_AMOUNT) AS "AVG PRICE"
FROM [Portfolio Projects]..[Miami Dade POs 2022]
GROUP BY ITEM_CATEGORY
ORDER BY COUNT(DISTINCT(PO_NUMBER)) DESC,  SUM(PO_QUANTITY) DESC
-- dont have access to a table that clarifies what each item category is--

SELECT BUSINESS_UNIT, COUNT(DISTINCT(PO_NUMBER)) AS "# OF ORDERS", AVG(PO_AMOUNT) AS "AVG PRICE"
FROM [Portfolio Projects]..[Miami Dade POs 2022]
GROUP BY BUSINESS_UNIT



--supplier % of total pos--

SELECT SUPPLIER_NAME, SUM(PO_AMOUNT) AS "TOTAL POs", (SUM(PO_AMOUNT) * 100)/ SUM(SUM(PO_AMOUNT)) OVER () AS "PCT TOTAL POs"
FROM [Portfolio Projects]..[Miami Dade POs 2022]
GROUP BY SUPPLIER_NAME
ORDER BY (SUM(PO_AMOUNT) * 100)/ SUM(SUM(PO_AMOUNT)) OVER () DESC
 
-- business unit % of total pos--
SELECT ISNULL(BUSINESS_UNIT, 'UNKNOWN'), (SUM(PO_AMOUNT) * 100)/ SUM(SUM(PO_AMOUNT)) OVER () AS "PCT TOTAL POs"
FROM [Portfolio Projects]..[Miami Dade POs 2022]
GROUP BY BUSINESS_UNIT
ORDER BY (SUM(PO_AMOUNT) * 100)/ SUM(SUM(PO_AMOUNT)) OVER () DESC

